### ISSUE TITLE
Instructions on how to import old notes

### ISSUE THREAD

**Issue by watou** [HolgerHatGarKeineNode/haven-docker#2]
Thank you very much for your Dockerisation of haven.  I've got it running with a cloudflared tunnel in the same process so the SSL cert and secure public accessibility are all solved neatly (see below).  I had to rebuild the image after removing `USER=nonroot` as my server gave no user a path to the project files.  The only remaining issue is, I don't know how to perform the one-time `--import` as is easy to do when not running in a container.  Do you have any advice or steps for this Docker novice?

```yaml
services:
  relay:
    container_name: haven
    image: haven-docker:latest
    env_file:
      - .env
    volumes:
      - "./db:/app/db"
      - "./templates:/app/templates"
      - "./blossom:/app/blossom"
      - "./relays_import.json:/app/relays_import.json"
      - "./relays_blastr.json:/app/relays_blastr.json"
    restart: unless-stopped
    networks:
      - haven
    labels:
      glance.name: Haven Relay
      glance.icon: /assets/haven.png
      glance.url: https://relay.example.com
      glance.description: nostr relay
      glance.id: haven

  tunnel:
    container_name: cloudflared-haven-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=<YOUR_TOKEN>
    networks:
      - haven
    labels:
      glance.parent: haven
      glance.name: Haven Tunnel

networks:
  haven:
```
